name: 'Run Intellitester'
description: 'Run Intellitester E2E tests with preview server support'

inputs:
  test-file:
    description: 'Test file or directory to run (auto-discovers if omitted)'
    required: false
    default: ''
  browser:
    description: 'Browser to use (chrome, firefox, safari)'
    required: false
    default: 'chrome'
  preview:
    description: 'Build and run against preview server'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for tests'
    required: false
    default: '.'
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  package-manager:
    description: 'Package manager (npm, pnpm, yarn, bun)'
    required: false
    default: 'pnpm'
  npm-registry:
    description: 'Custom npm registry URL for private packages'
    required: false
    default: ''
  npm-token:
    description: 'NPM auth token for private registry'
    required: false
    default: ''
  env-file:
    description: 'Content for .env file (multiline)'
    required: false
    default: ''
  playwright-browsers:
    description: 'Playwright browsers to install (chromium, firefox, webkit)'
    required: false
    default: 'chromium'
  prod:
    description: 'Alias for preview - build and serve production build'
    required: false
    default: 'false'
  fresh-build:
    description: 'Force a fresh build (default: skips build if artifacts exist)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install package manager
      if: inputs.package-manager != 'npm'
      shell: bash
      run: npm install -g ${{ inputs.package-manager }}@latest

    - name: Configure npm registry
      if: inputs.npm-registry != ''
      shell: bash
      env:
        REGISTRY: ${{ inputs.npm-registry }}
        NPM_TOKEN: ${{ inputs.npm-token }}
      run: |
        # Extract org for scoped registry (GitHub/GitLab package style URLs)
        if [[ "$REGISTRY" == *"/npm/"* ]]; then
          ORG=$(echo "$REGISTRY" | sed -n 's|.*/packages/\([^/]*\)/npm/.*|\1|p')
          [[ -n "$ORG" ]] && echo "@${ORG}:registry=${REGISTRY}" >> ~/.npmrc
        fi
        # Add auth token if provided
        if [[ -n "$NPM_TOKEN" ]]; then
          HOST=$(echo "$REGISTRY" | sed 's|https\?://||; s|/$||')
          echo "//${HOST}:_authToken=${NPM_TOKEN}" >> ~/.npmrc
        fi

    - name: Create .env file
      if: inputs.env-file != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ENV_CONTENT: ${{ inputs.env-file }}
      run: printf '%s\n' "$ENV_CONTENT" > .env

    - name: Ensure playwright and intellitester installed
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PM: ${{ inputs.package-manager }}
        ACTION_REF: ${{ github.action_ref }}
        WORK_DIR: ${{ inputs.working-directory }}
      run: |
        add_dev() {
          # Detect workspace from working directory
          IS_WORKSPACE="false"
          WORKSPACE_ROOT=""

          # Check if pnpm-workspace.yaml exists in WORK_DIR or any parent
          CHECK_DIR="$WORK_DIR"
          while true; do
            if [[ -f "$CHECK_DIR/pnpm-workspace.yaml" ]]; then
              IS_WORKSPACE="true"
              WORKSPACE_ROOT="$CHECK_DIR"
              break
            fi
            PARENT=$(dirname "$CHECK_DIR")
            # Stop if we've reached the root or haven't moved
            if [[ "$PARENT" == "$CHECK_DIR" ]] || [[ "$PARENT" == "/" ]] || [[ "$PARENT" == "." && "$CHECK_DIR" == "." ]]; then
              break
            fi
            CHECK_DIR="$PARENT"
          done

          # If not pnpm workspace, check for npm/yarn workspaces
          if [[ "$IS_WORKSPACE" == "false" ]]; then
            CHECK_DIR="$WORK_DIR"
            while true; do
              if grep -q '"workspaces"' "$CHECK_DIR/package.json" 2>/dev/null; then
                IS_WORKSPACE="true"
                WORKSPACE_ROOT="$CHECK_DIR"
                break
              fi
              PARENT=$(dirname "$CHECK_DIR")
              if [[ "$PARENT" == "$CHECK_DIR" ]] || [[ "$PARENT" == "/" ]] || [[ "$PARENT" == "." && "$CHECK_DIR" == "." ]]; then
                break
              fi
              CHECK_DIR="$PARENT"
            done
          fi

          # Find workspace package directory (relative path for pnpm/yarn/npm, absolute for bun)
          WORKSPACE_PKG_DIR=""
          if [[ "$IS_WORKSPACE" == "true" ]]; then
            # Check if working directory has package.json (it's a workspace package)
            if [[ -f "$WORK_DIR/package.json" ]]; then
              # For bun: absolute path; for others: relative to workspace root
              WORKSPACE_PKG_DIR="$WORK_DIR"
            else
              # Walk up to find a workspace package
              WALK_DIR="$WORK_DIR"
              while [[ "$WALK_DIR" != "." && "$WALK_DIR" != "" ]]; do
                if [[ -f "$WALK_DIR/package.json" ]]; then
                  WORKSPACE_PKG_DIR="$WALK_DIR"
                  break
                fi
                WALK_DIR=$(dirname "$WALK_DIR")
              done
            fi

            # Fail if workspace package not found
            if [[ -z "$WORKSPACE_PKG_DIR" ]]; then
              echo "Error: Could not detect workspace package directory."
              echo "Please specify 'working-directory' pointing to your workspace package."
              exit 1
            fi
          fi

          case "$PM" in
            pnpm)
              if [[ -n "$WORKSPACE_PKG_DIR" ]]; then
                # Calculate relative path from workspace root to package dir
                if [[ "$WORKSPACE_PKG_DIR" == "$WORKSPACE_ROOT" || "$WORKSPACE_PKG_DIR" == "." ]]; then
                  # Package is at workspace root - no filter needed, use --workspace-root
                  pnpm add -D -w "$1"
                else
                  REL_PATH="${WORKSPACE_PKG_DIR#$WORKSPACE_ROOT/}"
                  pnpm add -D --filter "./$REL_PATH" "$1"
                fi
              else
                pnpm add -D "$1"
              fi
              ;;
            yarn)
              if [[ -n "$WORKSPACE_PKG_DIR" ]]; then
                # Calculate relative path from workspace root to package dir
                if [[ "$WORKSPACE_PKG_DIR" == "$WORKSPACE_ROOT" || "$WORKSPACE_PKG_DIR" == "." ]]; then
                  # Package is at workspace root - add directly
                  yarn add -D "$1"
                else
                  REL_PATH="${WORKSPACE_PKG_DIR#$WORKSPACE_ROOT/}"
                  yarn add -D --workspace "./$REL_PATH" "$1"
                fi
              else
                yarn add -D "$1"
              fi
              ;;
            bun)
              # Bun: use --cwd with absolute path
              if [[ -n "$WORKSPACE_PKG_DIR" ]]; then
                bun add -D "$1" --cwd "$WORKSPACE_PKG_DIR"
              else
                bun add -D "$1"
              fi
              ;;
            *)
              # npm workspaces
              if [[ -n "$WORKSPACE_PKG_DIR" ]]; then
                # Calculate relative path from workspace root to package dir
                if [[ "$WORKSPACE_PKG_DIR" == "$WORKSPACE_ROOT" || "$WORKSPACE_PKG_DIR" == "." ]]; then
                  # Package is at workspace root - add directly
                  npm install -D "$1"
                else
                  REL_PATH="${WORKSPACE_PKG_DIR#$WORKSPACE_ROOT/}"
                  npm install -D --workspace "./$REL_PATH" "$1"
                fi
              else
                npm install -D "$1"
              fi
              ;;
          esac
        }
        # Get version from action ref (e.g., v0.2.23 -> 0.2.23)
        ACTION_VERSION="${ACTION_REF#v}"
        grep -q '"playwright"' "$WORK_DIR/package.json" 2>/dev/null || add_dev playwright@latest
        grep -q '"intellitester"' "$WORK_DIR/package.json" 2>/dev/null || add_dev "intellitester@${ACTION_VERSION:-latest}"

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.package-manager }} install

    - name: Get Playwright version
      id: pw-version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Try lockfiles first, fall back to installed package
        if [[ -f pnpm-lock.yaml ]]; then
          VER=$(grep -A2 "playwright:" pnpm-lock.yaml | grep "version:" | head -1 | sed "s/.*version: '\{0,1\}\([^']*\)'\{0,1\}/\1/")
        elif [[ -f package-lock.json ]]; then
          VER=$(node -e "console.log(require('./package-lock.json').packages?.['node_modules/playwright']?.version || '')")
        elif [[ -f yarn.lock ]]; then
          VER=$(grep -A1 '^"*playwright@' yarn.lock | grep "version" | head -1 | sed 's/.*"\([^"]*\)".*/\1/')
        elif [[ -f bun.lockb ]]; then
          VER=$(node -e "console.log(require('./node_modules/playwright/package.json').version)" 2>/dev/null || echo "")
        fi
        VER=${VER:-$(node -e "console.log(require('./node_modules/playwright/package.json').version)" 2>/dev/null || echo "latest")}
        echo "version=$VER" >> "$GITHUB_OUTPUT"

    - name: Cache Playwright browsers
      id: pw-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.pw-version.outputs.version }}-${{ inputs.playwright-browsers }}

    - name: Install Playwright browsers
      if: steps.pw-cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npx playwright install --with-deps ${{ inputs.playwright-browsers }}

    - name: Install Playwright system deps (cached browsers)
      if: steps.pw-cache.outputs.cache-hit == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npx playwright install-deps ${{ inputs.playwright-browsers }}

    - name: Run Intellitester
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npx intellitester run \
          ${{ inputs.test-file }} \
          ${{ inputs.preview == 'true' && '--preview' || '' }} \
          ${{ inputs.prod == 'true' && '--prod' || '' }} \
          ${{ inputs.fresh-build == 'true' && '--fresh-build' || '' }} \
          --browser ${{ inputs.browser }}
