name: 'Run Intellitester'
description: 'Run Intellitester E2E tests with preview server support'

inputs:
  test-file:
    description: 'Test file or directory to run (auto-discovers if omitted)'
    required: false
    default: ''
  browser:
    description: 'Browser to use (chrome, firefox, safari)'
    required: false
    default: 'chrome'
  preview:
    description: 'Build and run against preview server'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for tests'
    required: false
    default: '.'
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  package-manager:
    description: 'Package manager (npm, pnpm, yarn, bun)'
    required: false
    default: 'pnpm'
  npm-registry:
    description: 'Custom npm registry URL for private packages'
    required: false
    default: ''
  npm-token:
    description: 'NPM auth token for private registry'
    required: false
    default: ''
  env-file:
    description: 'Content for .env file (multiline)'
    required: false
    default: ''
  playwright-browsers:
    description: 'Playwright browser to install (chromium, firefox, webkit)'
    required: false
    default: 'chromium'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install package manager
      shell: bash
      run: |
        if [ "${{ inputs.package-manager }}" = "pnpm" ]; then
          npm install -g pnpm@latest
        elif [ "${{ inputs.package-manager }}" = "yarn" ]; then
          npm install -g yarn
        elif [ "${{ inputs.package-manager }}" = "bun" ]; then
          npm install -g bun
        fi

    - name: Configure npm registry
      if: inputs.npm-registry != ''
      shell: bash
      run: |
        REGISTRY="${{ inputs.npm-registry }}"
        # Extract scope from registry URL if it's a scoped registry
        if [[ "$REGISTRY" == *"/npm/"* ]]; then
          # Forgejo/Gitea style: extract org name
          ORG=$(echo "$REGISTRY" | sed -n 's|.*/packages/\([^/]*\)/npm/.*|\1|p')
          if [ -n "$ORG" ]; then
            echo "@${ORG}:registry=${REGISTRY}" >> ~/.npmrc
          fi
        fi
        # Add auth token
        if [ -n "${{ inputs.npm-token }}" ]; then
          # Extract host from URL
          HOST=$(echo "$REGISTRY" | sed 's|https\?://||' | sed 's|/$||')
          echo "//${HOST}:_authToken=${{ inputs.npm-token }}" >> ~/.npmrc
        fi

    - name: Install Intellitester
      shell: bash
      run: npm install -g intellitester

    - name: Create .env file
      if: inputs.env-file != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cat > .env << 'ENVEOF'
        ${{ inputs.env-file }}
        ENVEOF

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.package-manager }} install

    - name: Install Playwright browsers
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npx playwright install --with-deps ${{ inputs.playwright-browsers }}

    - name: Run Intellitester
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ARGS=""
        if [ -n "${{ inputs.test-file }}" ]; then
          ARGS="${{ inputs.test-file }}"
        fi
        if [ "${{ inputs.preview }}" = "true" ]; then
          ARGS="$ARGS --preview"
        fi
        ARGS="$ARGS --browser ${{ inputs.browser }}"

        echo "Running: intellitester run $ARGS"
        intellitester run $ARGS
        EXIT_CODE=$?

        if [ $EXIT_CODE -ne 0 ]; then
          echo "::error::Intellitester tests failed with exit code $EXIT_CODE"
          exit $EXIT_CODE
        fi
