name: 'Run Intellitester'
description: 'Run Intellitester E2E tests with preview server support'

inputs:
  test-file:
    description: 'Test file or directory to run (auto-discovers if omitted)'
    required: false
    default: ''
  browser:
    description: 'Browser to use (chrome, firefox, safari)'
    required: false
    default: 'chrome'
  preview:
    description: 'Build and run against preview server'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for tests'
    required: false
    default: '.'
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  package-manager:
    description: 'Package manager (npm, pnpm, yarn, bun)'
    required: false
    default: 'pnpm'
  npm-registry:
    description: 'Custom npm registry URL for private packages'
    required: false
    default: ''
  npm-token:
    description: 'NPM auth token for private registry'
    required: false
    default: ''
  env-file:
    description: 'Content for .env file (multiline)'
    required: false
    default: ''
  playwright-browsers:
    description: 'Playwright browsers to install (chromium, firefox, webkit)'
    required: false
    default: 'chromium'
  prod:
    description: 'Alias for preview - build and serve production build'
    required: false
    default: 'false'
  fresh-build:
    description: 'Force a fresh build (default: skips build if artifacts exist)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install package manager
      if: inputs.package-manager != 'npm'
      shell: bash
      run: npm install -g ${{ inputs.package-manager }}@latest

    - name: Configure npm registry
      if: inputs.npm-registry != ''
      shell: bash
      env:
        REGISTRY: ${{ inputs.npm-registry }}
        NPM_TOKEN: ${{ inputs.npm-token }}
      run: |
        # Extract org for scoped registry (GitHub/GitLab package style URLs)
        if [[ "$REGISTRY" == *"/npm/"* ]]; then
          ORG=$(echo "$REGISTRY" | sed -n 's|.*/packages/\([^/]*\)/npm/.*|\1|p')
          [[ -n "$ORG" ]] && echo "@${ORG}:registry=${REGISTRY}" >> ~/.npmrc
        fi
        # Add auth token if provided
        if [[ -n "$NPM_TOKEN" ]]; then
          HOST=$(echo "$REGISTRY" | sed 's|https\?://||; s|/$||')
          echo "//${HOST}:_authToken=${NPM_TOKEN}" >> ~/.npmrc
        fi

    - name: Create .env file
      if: inputs.env-file != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ENV_CONTENT: ${{ inputs.env-file }}
      run: printf '%s\n' "$ENV_CONTENT" > .env

    - name: Ensure playwright and intellitester installed
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        PM: ${{ inputs.package-manager }}
        ACTION_REF: ${{ github.action_ref }}
        WORK_DIR: ${{ inputs.working-directory }}
      run: |
        add_dev() {
          # Detect workspace from working directory
          IS_WORKSPACE="false"
          if [[ -f "$WORK_DIR/pnpm-workspace.yaml" ]] || grep -q '"workspaces"' "$WORK_DIR/package.json" 2>/dev/null; then
            IS_WORKSPACE="true"
          fi

          # For Bun: find the workspace from working directory
          BUN_WORKSPACE_DIR=""
          if [[ "$PM" == "bun" && "$IS_WORKSPACE" == "true" ]]; then
            # Start from working directory, walk up to find workspace package.json
            CURRENT_DIR="$WORK_DIR"
            # Remove leading ./ if present
            CURRENT_DIR="${CURRENT_DIR#./}"
            # If working-directory is root, try to find any workspace
            if [[ -z "$CURRENT_DIR" || "$CURRENT_DIR" == "." ]]; then
              # Try to find first workspace directory
              WORKSPACES=$(grep -o '"workspaces": \[[^]]*\]' "$WORK_DIR/package.json" 2>/dev/null | grep -o '"[^"]*"' | tr -d '"' | head -1)
              if [[ -n "$WORKSPACES" ]]; then
                # Expand glob pattern to find first workspace
                BUN_WORKSPACE_DIR=$(find "$WORK_DIR/$WORKSPACES" -mindepth 1 -maxdepth 2 -name "package.json" -exec dirname {} \; | head -1)
              fi
            else
              # Check if working-directory has package.json (it's a workspace)
              if [[ -f "$WORK_DIR/package.json" ]]; then
                BUN_WORKSPACE_DIR="$WORK_DIR"
              else
                # Walk up from working directory to find workspace
                WALK_DIR="$WORK_DIR"
                while [[ "$WALK_DIR" != "." && "$WALK_DIR" != "" ]]; do
                  if [[ -f "$WALK_DIR/package.json" ]]; then
                    BUN_WORKSPACE_DIR="$WALK_DIR"
                    break
                  fi
                  WALK_DIR=$(dirname "$WALK_DIR")
                done
              fi
            fi

            # Fail if workspace not found
            if [[ -z "$BUN_WORKSPACE_DIR" ]]; then
              echo "Error: Could not detect Bun workspace directory."
              echo "Please specify 'working-directory' pointing to your workspace, or ensure your workspace has a package.json"
              exit 1
            fi
          fi

          case "$PM" in
            pnpm)
              if [[ "$IS_WORKSPACE" == "true" ]]; then
                pnpm add -D -w "$1"  # -w = --workspace-root
              else
                pnpm add -D "$1"
              fi
              ;;
            yarn)
              if [[ "$IS_WORKSPACE" == "true" ]]; then
                yarn add -D -W "$1"  # -W (capital W) = workspace root
              else
                yarn add -D "$1"
              fi
              ;;
            bun)
              # Bun: use --cwd to add to specific workspace directory
              if [[ -n "$BUN_WORKSPACE_DIR" ]]; then
                bun add -D "$1" --cwd "$BUN_WORKSPACE_DIR"
              else
                bun add -D "$1"
              fi
              ;;
            *)
              # npm workspaces - use -w . for root workspace
              if [[ "$IS_WORKSPACE" == "true" ]]; then
                npm install -D -w . "$1"
              else
                npm install -D "$1"
              fi
              ;;
          esac
        }
        # Get version from action ref (e.g., v0.2.23 -> 0.2.23)
        ACTION_VERSION="${ACTION_REF#v}"
        grep -q '"playwright"' "$WORK_DIR/package.json" 2>/dev/null || add_dev playwright@latest
        grep -q '"intellitester"' "$WORK_DIR/package.json" 2>/dev/null || add_dev "intellitester@${ACTION_VERSION:-latest}"

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.package-manager }} install

    - name: Get Playwright version
      id: pw-version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Try lockfiles first, fall back to installed package
        if [[ -f pnpm-lock.yaml ]]; then
          VER=$(grep -A2 "playwright:" pnpm-lock.yaml | grep "version:" | head -1 | sed "s/.*version: '\{0,1\}\([^']*\)'\{0,1\}/\1/")
        elif [[ -f package-lock.json ]]; then
          VER=$(node -e "console.log(require('./package-lock.json').packages?.['node_modules/playwright']?.version || '')")
        elif [[ -f yarn.lock ]]; then
          VER=$(grep -A1 '^"*playwright@' yarn.lock | grep "version" | head -1 | sed 's/.*"\([^"]*\)".*/\1/')
        elif [[ -f bun.lockb ]]; then
          VER=$(node -e "console.log(require('./node_modules/playwright/package.json').version)" 2>/dev/null || echo "")
        fi
        VER=${VER:-$(node -e "console.log(require('./node_modules/playwright/package.json').version)" 2>/dev/null || echo "latest")}
        echo "version=$VER" >> "$GITHUB_OUTPUT"

    - name: Cache Playwright browsers
      id: pw-cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          ~/AppData/Local/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.pw-version.outputs.version }}-${{ inputs.playwright-browsers }}

    - name: Install Playwright browsers
      if: steps.pw-cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npx playwright install --with-deps ${{ inputs.playwright-browsers }}

    - name: Install Playwright system deps (cached browsers)
      if: steps.pw-cache.outputs.cache-hit == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npx playwright install-deps ${{ inputs.playwright-browsers }}

    - name: Run Intellitester
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npx intellitester run \
          ${{ inputs.test-file }} \
          ${{ inputs.preview == 'true' && '--preview' || '' }} \
          ${{ inputs.prod == 'true' && '--prod' || '' }} \
          ${{ inputs.fresh-build == 'true' && '--fresh-build' || '' }} \
          --browser ${{ inputs.browser }}
