name: 'Run Intellitester'
description: 'Run Intellitester E2E tests with preview server support'

inputs:
  test-file:
    description: 'Test file or directory to run (auto-discovers if omitted)'
    required: false
    default: ''
  browser:
    description: 'Browser to use (chrome, firefox, safari)'
    required: false
    default: 'chrome'
  preview:
    description: 'Build and run against preview server'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for tests'
    required: false
    default: '.'
  node-version:
    description: 'Node.js version'
    required: false
    default: '22'
  package-manager:
    description: 'Package manager (npm, pnpm, yarn, bun)'
    required: false
    default: 'pnpm'
  npm-registry:
    description: 'Custom npm registry URL for private packages'
    required: false
    default: ''
  npm-token:
    description: 'NPM auth token for private registry'
    required: false
    default: ''
  env-file:
    description: 'Content for .env file (multiline)'
    required: false
    default: ''
  playwright-browsers:
    description: 'Playwright browser to install (chromium, firefox, webkit)'
    required: false
    default: 'chromium'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install package manager
      shell: bash
      run: |
        set -e
        if [ "${{ inputs.package-manager }}" = "pnpm" ]; then
          npm install -g pnpm@latest
        elif [ "${{ inputs.package-manager }}" = "yarn" ]; then
          npm install -g yarn
        elif [ "${{ inputs.package-manager }}" = "bun" ]; then
          npm install -g bun
        fi

    - name: Configure npm registry
      if: inputs.npm-registry != ''
      shell: bash
      run: |
        set -e
        REGISTRY="${{ inputs.npm-registry }}"
        if [[ "$REGISTRY" == *"/npm/"* ]]; then
          ORG=$(echo "$REGISTRY" | sed -n 's|.*/packages/\([^/]*\)/npm/.*|\1|p')
          if [ -n "$ORG" ]; then
            echo "@${ORG}:registry=${REGISTRY}" >> ~/.npmrc
          fi
        fi
        if [ -n "${{ inputs.npm-token }}" ]; then
          HOST=$(echo "$REGISTRY" | sed 's|https\?://||' | sed 's|/$||')
          echo "//${HOST}:_authToken=${{ inputs.npm-token }}" >> ~/.npmrc
        fi

    - name: Create .env file
      if: inputs.env-file != ''
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cat > .env << 'ENVEOF'
        ${{ inputs.env-file }}
        ENVEOF

    - name: Ensure intellitester and playwright are installed
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -e
        PM="${{ inputs.package-manager }}"

        # Check if playwright is in package.json, add if not
        if ! grep -q '"playwright"' package.json 2>/dev/null; then
          echo "Adding playwright as devDependency..."
          if [ "$PM" = "pnpm" ]; then
            pnpm add -D playwright@latest
          elif [ "$PM" = "yarn" ]; then
            yarn add -D playwright@latest
          elif [ "$PM" = "bun" ]; then
            bun add -D playwright@latest
          else
            npm install -D playwright@latest
          fi
        fi

        # Check if intellitester is in package.json, add if not
        if ! grep -q '"intellitester"' package.json 2>/dev/null; then
          echo "Adding intellitester as devDependency..."
          if [ "$PM" = "pnpm" ]; then
            pnpm add -D intellitester@latest
          elif [ "$PM" = "yarn" ]; then
            yarn add -D intellitester@latest
          elif [ "$PM" = "bun" ]; then
            bun add -D intellitester@latest
          else
            npm install -D intellitester@latest
          fi
        fi

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -e
        ${{ inputs.package-manager }} install

    - name: Install Playwright browsers
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -e
        npx playwright install --with-deps ${{ inputs.playwright-browsers }}

    - name: Run Intellitester
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -e
        ARGS=""
        if [ -n "${{ inputs.test-file }}" ]; then
          ARGS="${{ inputs.test-file }}"
        fi
        if [ "${{ inputs.preview }}" = "true" ]; then
          ARGS="$ARGS --preview"
        fi
        ARGS="$ARGS --browser ${{ inputs.browser }}"

        echo "Running: npx intellitester run $ARGS"
        npx intellitester run $ARGS
