name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        type: string
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

concurrency:
  group: docker-${{ inputs.version || github.sha }}
  cancel-in-progress: false

env:
  REGISTRY: forge.blackleafdigital.com
  IMAGE_NAME: blackleafdigital/autotester

jobs:
  # ===========================================
  # Determine Version
  # ===========================================
  version:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            # Get the latest tag from git
            VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          fi

          if [ -z "$VERSION" ]; then
            echo "ERROR: No version found"
            exit 1
          fi

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${VERSION#v}" >> $GITHUB_OUTPUT
          echo "Building Docker image for version: ${VERSION}"

  # ===========================================
  # Build and Push Docker Image
  # ===========================================
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.FORGEJO_ACTIONS_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ needs.version.outputs.version }}
            type=raw,value=v${{ needs.version.outputs.tag }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ needs.version.outputs.tag }}

      - name: Image digest
        run: |
          echo "Image pushed successfully!"
          echo "Tags:"
          echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' | sed 's/^/  - /'
          echo ""
          echo "Pull with:"
          echo "  docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          echo "  docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.version.outputs.version }}"
