name: Publish NPM Package

on:
  # Only manual/API trigger - CI will call this after success on tags
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0)'
        required: true
        type: string
      dry_run:
        description: 'Dry run (no actual publish)'
        required: false
        default: false
        type: boolean

concurrency:
  group: publish-package
  cancel-in-progress: false

env:
  NODE_VERSION: '22'
  PNPM_VERSION: '10'
  REGISTRY: forge.blackleafdigital.com
  REGISTRY_SCOPE: '@blackleafdigital'

jobs:
  # ===========================================
  # Determine Version
  # ===========================================
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Determine version
        id: version
        run: |
          VERSION="${{ inputs.version }}"
          if [ -z "$VERSION" ]; then
            echo "ERROR: No version provided"
            exit 1
          fi
          # Remove 'v' prefix if present
          TAG="${VERSION#v}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "Building release: ${VERSION} (tag: ${TAG})"

  # ===========================================
  # Build and Publish to npm Registry
  # ===========================================
  publish-npm:
    name: Publish to Forgejo npm Registry
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        run: npm install -g pnpm@${{ env.PNPM_VERSION }}

      - name: Configure npm auth
        run: |
          echo "//forge.blackleafdigital.com/api/packages/blackleafdigital/npm/:_authToken=${{ secrets.FORGEJO_ACTIONS_TOKEN }}" >> ~/.npmrc
          echo "registry=https://forge.blackleafdigital.com/api/packages/blackleafdigital/npm/" >> ~/.npmrc

      - name: Restore cache
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: restore
          key: pnpm-publish-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ~/.local/share/pnpm/store
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Update version in package.json
        run: |
          VERSION="${{ needs.version.outputs.tag }}"
          # Update root package.json
          pnpm version ${VERSION} --no-git-tag-version
          # Update workspace packages if they exist
          if [ -d "packages/astro-integration" ]; then
            cd packages/astro-integration
            pnpm version ${VERSION} --no-git-tag-version
            cd ../..
          fi
          if [ -d "packages/vite-plugin-autotester" ]; then
            cd packages/vite-plugin-autotester
            pnpm version ${VERSION} --no-git-tag-version
            cd ../..
          fi

      - name: Publish to registry
        if: ${{ inputs.dry_run != 'true' }}
        run: |
          # Publish root package
          pnpm publish --no-git-checks --registry https://forge.blackleafdigital.com/api/packages/blackleafdigital/npm/

          # Publish workspace packages if they exist
          if [ -d "packages/astro-integration" ]; then
            cd packages/astro-integration
            pnpm publish --no-git-checks --registry https://forge.blackleafdigital.com/api/packages/blackleafdigital/npm/
            cd ../..
          fi

          if [ -d "packages/vite-plugin-autotester" ]; then
            cd packages/vite-plugin-autotester
            pnpm publish --no-git-checks --registry https://forge.blackleafdigital.com/api/packages/blackleafdigital/npm/
            cd ../..
          fi

      - name: Publish Dry Run
        if: ${{ inputs.dry_run == 'true' }}
        run: |
          echo "DRY RUN - Would publish packages version ${{ needs.version.outputs.tag }}"
          echo "Root package: autotester@${{ needs.version.outputs.tag }}"
          if [ -d "packages/astro-integration" ]; then
            echo "Workspace package: astro-integration@${{ needs.version.outputs.tag }}"
          fi
          if [ -d "packages/vite-plugin-autotester" ]; then
            echo "Workspace package: vite-plugin-autotester@${{ needs.version.outputs.tag }}"
          fi

      - name: Save cache
        if: always()
        uses: https://forge.blackleafdigital.com/BlackLeafDigital/actions/s3-cache@main
        with:
          mode: save
          key: pnpm-publish-${{ hashFiles('**/pnpm-lock.yaml') }}
          path: ~/.local/share/pnpm/store
          bucket: ${{ secrets.S3_BUCKET }}
          endpoint: https://${{ secrets.S3_ENDPOINT }}
          region: ${{ secrets.S3_REGION }}
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_ACCESS_SECRET }}

  # ===========================================
  # Create Forgejo Release
  # ===========================================
  create-release:
    name: Create Forgejo Release
    runs-on: ubuntu-latest
    needs: [version, publish-npm]
    if: ${{ inputs.dry_run != 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          VERSION="${{ needs.version.outputs.version }}"

          # Get commits since last tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            COMMITS=$(git log ${PREV_TAG}..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi

          # Save to file for multiline handling
          cat > /tmp/changelog.txt << EOF
          ## AutoTester ${{ needs.version.outputs.version }}

          ### Changes
          ${COMMITS}

          ### Installation

          #### npm
          \`\`\`bash
          npm install autotester@${{ needs.version.outputs.tag }}
          \`\`\`

          #### pnpm
          \`\`\`bash
          pnpm add autotester@${{ needs.version.outputs.tag }}
          \`\`\`

          #### CLI
          \`\`\`bash
          npx autotester@${{ needs.version.outputs.tag }}
          \`\`\`

          ### Packages Published
          - autotester@${{ needs.version.outputs.tag }}

          Published to: https://forge.blackleafdigital.com/blackleafdigital/-/packages/npm/autotester
          EOF

      - name: Create Forgejo Release
        run: |
          VERSION="${{ needs.version.outputs.version }}"
          TAG="${{ needs.version.outputs.tag }}"

          # Read changelog
          BODY=$(cat /tmp/changelog.txt)

          # Determine if prerelease
          PRERELEASE="false"
          if echo "${VERSION}" | grep -qE '(alpha|beta|rc)'; then
            PRERELEASE="true"
          fi

          # Create release via Forgejo API
          RESPONSE=$(curl -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_ACTIONS_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://forge.blackleafdigital.com/api/v1/repos/${{ github.repository }}/releases" \
            -d "{
              \"tag_name\": \"${VERSION}\",
              \"name\": \"AutoTester ${VERSION}\",
              \"body\": $(echo "$BODY" | jq -Rs .),
              \"draft\": false,
              \"prerelease\": ${PRERELEASE}
            }")

          RELEASE_ID=$(echo "$RESPONSE" | jq -r '.id')

          if [ "$RELEASE_ID" = "null" ] || [ -z "$RELEASE_ID" ]; then
            echo "ERROR: Failed to create release"
            echo "$RESPONSE" | jq .
            exit 1
          fi

          echo "Created release ID: $RELEASE_ID"
          echo "Release URL: https://forge.blackleafdigital.com/${{ github.repository }}/releases/tag/${VERSION}"
